### PR TITLE
Items

### PR DESCRIPTION
**Pull request by weisspe**
Mostly armor

### CODE REVIEW

**Comment by BananaFlambe** [comment]
Yep, perfect! good work!

**Comment by weisspe** [comment]
@Crevox yeah I was sort of surprised at raptor too.

**Comment by Crevox** [comment]
I was referencing your repeated mispelling of "Gauntlet" :P

**Comment by weisspe** [comment]
Dangit.  I'll have to fix that real quick.  I use find and replace since there are 5 or 6 of the same item so that's how it happened :(

**Pull request merged**
