### PR TITLE
Ability Names

### PR DESCRIPTION
**Pull request by nappycat**
I hope this is how I'm supposed to do this. I switched shrink to reduce and resource exploration to gathering (a la monster hunter), but wasn't entirely sure if there was some prior context. I tried keeping skill names consistent with the original game. Hope this helps.

### CODE REVIEW

**Comment by Crevox** [comment]
This is great! I'm going to take a moment or two to go over these additions and the other pull request.

My only concerns with the names here is that some of them may be too long. We don't have very much room for ability names within the game, as all of them only use two characters normally. We already have some in-game that are pushing it, so you may want to use those as a reference and truncate some of these additions.

**Comment by nappycat** [comment]
Ahh, right, I was worried about that. Can you give an example of one that would be on the verge of being too long?

**Comment by Crevox** [comment]
I'm not able to login to the game at the moment to check.

**Comment by Crevox** [comment]
Here is an example. I would say this is the limit. If a name was any longer than this, then there would be overlap on the "GET" button and some menus would turn the text into super squish mode.

image

**Pull request merged**
