### PR TITLE
craft and some dialog

### PR DESCRIPTION
**Pull request by oldmadmax**

### CODE REVIEW

**Comment by Crevox** [comment]
There are so many errors with this. Please do not merge this until it is fixed.

**Comment by oldmadmax** [comment]
like what

**Comment by Crevox** [comment]
1. Lacking punctuation, random capitalization for no reason
2. Poor grammar (craft_res line 192, 204, 216, 220, 413, 428, so many others)
3. Spelling errors (craft_res line 248, etc)
4. Syntax errors causing poor concatenation (craft_res line 436, 286, etc)
5. These errors also exist in the bazaar and shop files, and they will probably be reverted entirely

**Comment by oldmadmax** [comment]
I see you girls wanna fuck with this like if you translating Shakespeare to Braille ... be my guest and do it yourself ... just please finish before english release ... im going kill some dragons in meantime... kisses

**Comment by Jowdan3006** [comment]
We're trying to work to a certain standard as all. No need to get salty about it.

**Comment by oldmadmax** [comment]
I really wish to be there , see your faces when you f first time be able to see your "translation" in game ... like really ... 
but you know what , just download the "new" patch and see for yourself, how it looks like when things are to long for example. I mean if you be able to recognize letters  ... maybe then you understand what im talking about.
Or check crystal patch and see how skill menu looks like after 7+ updates ... lol...
Are you people ever done this before?

ps:
and good remember this two words "shorten" and "simplify" you gonna use them a lot , that is if you be able to pack your shit and finally see it in game ...  bye

ps2:
and one more thing - on present project stage dont poke you long nose in other people work if you was not asked for advice or help

**Comment by Jowdan3006** [comment]
All translation patches done up till now have been by Riftcrystal alone, hence the slow updates aswell as lack of testing. Any mistakes in line length, overlapping elements ingame and whatever else will be fixed when seen, but currently it's not something we can test without making a new patch and seeing the mistakes in game. Spelling and punctuation however can be checked now before it's implemented into the patch, making it look more polished and less of a direct broken google translate.

I'm going to guess that English isn't your first language, as your comment is yet again riddled with spelling and punctuation mistakes. Which is fine, but it doesn't mean it's acceptable to include into the final patches without being looked over and edited. If you have a problem with that, then I suggest you fix your own mistakes so we (mostly crevox) don't have to, or pack up and leave.

**Pull request closed without merging**
