### PR TITLE
Achievement Names

### PR DESCRIPTION
**Pull request by weisspe**
Got a lot of the names covered.  There's still a fair amount left but
they look like they use a lot of nuance.

### CODE REVIEW

**Comment by Crevox** [comment]
A little concerned about "Liquid Puppet"... what enemy is this supposed to be? Does it match up with something we already translated a different way? Or is it an enemy type?

https://github.com/SpartanVXL/DDO-Translation/blob/master/ui/00_message/enemy/enemy_name.xml

**Comment by weisspe** [comment]
Me too.  The achievement for killing them was called Puppet Crusher using katakana.  I did a search against the source branch for that enemy name but it only shows up in that achievement description.  I'll roll it back if it's still too weird, I just figured it was worth seeing how other people feel.

Also, I'm not sure what enemy it would match up to.

**Comment by weisspe** [comment]
Oh, I just looked at my achievements in game and I have a fair amount of kills for the 'liquid puppet' one.  Based on the formatting of the description it's a category of enemy and not an actual enemy name, but I think Mudmen are in that category (I haven't been to too many areas yet so it's either them or slime/oozes).

**Comment by Crevox** [comment]
Yeah, I have to assume it's Mudmen/Sludgemen as a general enemy type. I wouldn't be against it.

**Comment by weisspe** [comment]
If I make it Sludgemen should we update the achievement name as well (and to what)?  Or should it stay Puppet Crusher and sound a little out of sync?

**Comment by Crevox** [comment]
Yeah, I'm not too sure. I can understand what they're going for, but I can't come up with the proper wording to make a good name. Sludgemen would be confusing because we would be referring to a specific enemy, but we're referring more to their family. It's not their enemy type, because they are "soft" enemies (aka, Formless).

I asked some people and they're basically in the same state of mind, thinking something like Viscous Doll or Liquid Doll etc. It's gonna be a flavor/preference thing, so I think I'd leave it up to you.

**Comment by weisspe** [comment]
I'm going to keep it as is then and if we get a better idea in the future we can update it.

**Pull request merged**
