### PR TITLE
Monster name translations

### PR DESCRIPTION
**Pull request by BananaFlambe**
Translated most of the names, please check them, Thank you :)

### CODE REVIEW

**Comment by BananaFlambe** [comment]
Can someone check this please? Thank you

**Comment by Haplo064** [comment]
Haplo- "Lizardmen" are actually "Saurian" in english, not sure if we're romanizing it though.
See: http://dragonsdogma.wikia.com/wiki/Saurian

**Comment by Crevox** [comment]
Comments, sorry this took so long:
1. "Mad man" man should be capitalized, and it probably should be "Mudman" instead (this is a sludgeman monster)
2. "Rogue Sekeer" it's seeker.
3. "Sulphur Saurian" spelling preference, Sulfur instead? might as well remain consistent with what riftcrystal has done.
4. "Skeleton Alchemist" I think this was translated to Alchemic Skeleton for riftcrystal, I don't necessarily disagree, he's not an alchemist, he's just alchemically enhanced

**Comment by BananaFlambe** [comment]
Thanks going to fix, but i'm not sure about the mud man, there's already a sludgeman monster, what do you say?

EDIT: is the alchemic skeleton suggestion valid for the other monsters too? (goblin etc.)

**Comment by Crevox** [comment]
There is but he's the same race of monster, so it seems like it's just a variant.

I think it's the same for the goblins/etc, yeah, if they are alchemists.

**Pull request merged**
